### ISSUE TITLE
help me next config

### ISSUE THREAD

**Issue by quyphan97** [uiwjs/react-markdown-preview#178]
how to configure next-translate & next-css. I tried to fix the picture but the error still occurs
![image](https://user-images.githubusercontent.com/59947963/158014598-6dd2ba0d-ba7b-41fe-b448-9621767e6b36.png)

**Comment by jaywcjlove** [comment]
@quyphan97 Provide an example via codesandbox.io?

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

**Comment by quyphan97** [comment]
Please help me. I looked at your example and applied it on typescript but it doesn't seem to work & mermaid doesn't work either [your example path](https://codesandbox.io/embed/markdown-editor-mermaid-for-react-uvtsx?fontsize=14&hidenavigation=1&theme=dark).
![image](https://user-images.githubusercontent.com/59947963/158105149-d07bfc8c-62b9-4ba3-b963-ba72aae17bea.png)

**Comment by jaywcjlove** [comment]
Provide an example via codesandbox.io?
@quyphan97

**Comment by quyphan97** [comment]
I tried to fix it but it works in [codesandbox](https://codesandbox.io/s/markdown-edior-eqzef8), but not in my project
![image](https://user-images.githubusercontent.com/59947963/158129352-0011653f-e9e6-4424-ada6-0b62fe689e89.png)

**Comment by quyphan97** [comment]
Is it a conflict with Form in antd?

**Comment by jaywcjlove** [comment]
@quyphan97 He is just a react component. I don't know what conflicts with antd?

**Comment by quyphan97** [comment]
I don't understand why when creating a test project on codesandbox it works, but applying the actual project gives the same error :((

**Comment by jaywcjlove** [comment]
There may be something wrong with your environment.
@quyphan97

**Comment by quyphan97** [comment]
Yes. thank you very much, i will keep checking if anything i will ask you again :(
