### ISSUE TITLE
examples how to use remark plugins

### ISSUE THREAD

**Issue by linojon** [uiwjs/react-markdown-preview#185]
hi, i'm looking for examples how to use remark plugins. The readme shows theres a prop `remarkPlugins` so i'm using that. Then it says `See the next section for examples on how to pass options` but i dont see a "next section" with an example. Specifically i want to add variables to the markdown and view the rendered values in the preview (https://github.com/mrzmmr/remark-variables) (and/or write my own simple preprocessor that does a .replaceAll on the markdown text before it is passed to the previewer.) Thanks!.

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-md-editor/issues/380#issuecomment-1116091874
