### ISSUE TITLE
Unordered and ordered list not showing correctly

### ISSUE THREAD

**Issue by sgalanb** [uiwjs/react-markdown-preview#200]
Using react-md-editor (v3.18.1) to write and this package (v4.1.0) to preview, i can't get to show the the dot of the unordered lists and the number of the ordered lists. Everything else works fine. 

I'm using Next.js v12.2.5 and the components as shown in the codebox example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js

![image](https://user-images.githubusercontent.com/73245438/187998928-0af8b349-6121-446f-89e9-f5de0fff4d34.png)

**Comment by sgalanb** [comment]
The marker doesn't appear at all.

![image](https://user-images.githubusercontent.com/73245438/188014070-51ca5b75-c02d-46ee-a049-52b1a9b2d7d4.png)

![image](https://user-images.githubusercontent.com/73245438/188012988-c7796219-ce91-4bb8-a85f-b7f8d85048cc.png)

**Comment by jaywcjlove** [comment]
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/1680273/188034822-0ae6d066-9cfb-4bd1-93da-ae5bf54ef1cc.png">

@sgalanb I test it works fine.

**Comment by sgalanb** [comment]
Just fixed it, it was the TailwindCSS package that sets the `list-style-type:` to `none` by default. In case someone has the same problem, just add this properties to your global css file:
```
@tailwind base;

@layer base {
  ul {
    @apply list-disc;
  }

  ol {
    @apply list-decimal;
  }
}
```

Thanks!
