### ISSUE TITLE
how to highlight the element 

### ISSUE THREAD

**Issue by CooperHash** [uiwjs/react-markdown-preview#201]
i don't know the property 'style' how it works, can anyone explain to me?

**Comment by jaywcjlove** [comment]
@CooperHash 


https://github.com/uiwjs/react-markdown-preview/blob/17734029155ec4a88da87cd098517b65291b52a0/src/index.tsx#L11

https://github.com/uiwjs/react-markdown-preview/blob/17734029155ec4a88da87cd098517b65291b52a0/src/index.tsx#L73


https://www.npmjs.com/package/rehype-prism-plus

**Comment by CooperHash** [comment]
thanks

**Comment by CooperHash** [comment]
> @CooperHash
> 
> https://github.com/uiwjs/react-markdown-preview/blob/17734029155ec4a88da87cd098517b65291b52a0/src/index.tsx#L11
> 
> https://github.com/uiwjs/react-markdown-preview/blob/17734029155ec4a88da87cd098517b65291b52a0/src/index.tsx#L73
> 
> https://www.npmjs.com/package/rehype-prism-plus

thanks
