### ISSUE TITLE
Remove browserslist "not dead" from package.json in v3.0.6

### ISSUE THREAD

**Issue by saran13raj** [uiwjs/react-markdown-preview#207]
Hi @jaywcjlove, we are restricted to use v3.0.6 because of react version and loader issues. 
But when we make a build of our CRA app we get into build error caused by borwserslist 

We found that removing "not dead" from browserslist fixed the issue.
Can we remove "browserslist": {} from package.json for this specific version or you could create a patch version fix for this?

**Comment by jaywcjlove** [comment]
@saran13raj Delete the following?

https://github.com/uiwjs/react-markdown-preview/blob/f331d5c1d448bcf5f963d3bfc30ac5eb69da0952/package.json#L100-L111

**Comment by saran13raj** [comment]
yes. that's right. @jaywcjlove

**Comment by jaywcjlove** [comment]
@saran13raj Upgrade `3.5.2`

**Comment by jaywcjlove** [comment]
@saran13raj Upgrade `3.5.2` or `4.1.4`
