### ISSUE TITLE
Is there a function to copy code blocks separately? How do I set it to enable this feature?

### ISSUE THREAD

**Issue by Yulingsong** [uiwjs/react-markdown-preview#220]
Copy code function like official documentation
<img width="926" alt="image" src="https://user-images.githubusercontent.com/13497831/233521043-4e991316-7007-46d2-8c5a-ed3f4b3c05e6.png">

**Comment by jaywcjlove** [comment]
@Yulingsong It was a bug and I fixed it.

**Comment by Yulingsong** [comment]
> @Yulingsong It was a bug and I fixed it.

If the plugin doesn't recognize the language, does it not support copy-paste?
like this
<img width="926" alt="image" src="https://user-images.githubusercontent.com/13497831/233817229-262006dd-9a8d-47c7-b1ba-18c6ee6a9823.png">

**Comment by jaywcjlove** [comment]
@Yulingsong Upgrade `v4.1.13`

**Comment by Yulingsong** [comment]
Thank you very much for your effective feedback
