### ISSUE TITLE
Why copyTextToClipboard does not work, I'm using Nextjs.

### ISSUE THREAD

**Issue by aholeye** [uiwjs/react-markdown-preview#227]

**Comment by jaywcjlove** [comment]
@aholeye Under normal circumstances, `@uiw/copy-to-clipboard` will not be compatible with `nextjs`, because it is just a function. But I still made a judgment.

I cannot reproduce your error.

**Comment by aholeye** [comment]
Yes, you are right. After testing, I found that when I used a component from shadcn ui, the copy button in the MarkdownPreview component inside their dialog component became ineffective. However, when I moved it from the dialog to a regular component, the issue disappeared.

**Comment by aholeye** [comment]
I found that the JavaScript copy to clipboard functionality indeed doesn't work when the dialog is open. I wasn't aware of this before and I apologize for wasting your time.
