### ISSUE TITLE
It does not respect it's container div's margins/boundaries

### ISSUE THREAD

**Issue by m-s-abeer** [uiwjs/react-markdown-preview#241]
If you notice this image, you'll see a code segment having a large single-line text going beyond its allowed margins
(uses react-markdown-preview)
![image](https://github.com/uiwjs/react-markdown-preview/assets/35918365/6863eee2-54ad-4d0e-883f-9c4b3e3718bd)

This is not the case on the editor though, you'll see it's view doesn't overflow it's parent div's boundary and rather creates a horizontal scrollbar to accommodate it.
(uses react-md-editor)
![image](https://github.com/uiwjs/react-markdown-preview/assets/35918365/232c3e54-ca7d-49b1-96c9-9ccdc7ad2ffd)

Maybe show scroll on overflow or wrap on overflow feature can be implemented? Please let me know, thanks! I just noticed this issue but I've already integrated this into my project which is going into production very soon. I would really appreciate your time. Thanks!

**Comment by jaywcjlove** [comment]
@m-s-abeer You can modify it through the style. The current style is consistent with the GitHub style.

**Comment by m-s-abeer** [comment]
Passing `style={{ width: '100%' }}` worked!
Thanks!
