### ISSUE TITLE
Add support for GitHub alerts / admonitions.

### ISSUE THREAD

**Issue by ajh123** [uiwjs/react-markdown-preview#258]
# Introduction

Alerts / admonitions are warning boxes which use markdown blockquotes. See [the docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) for more info.

### Markdown

```markdown
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
```

### Rendered

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.

**Comment by jaywcjlove** [comment]
@ajh123 Upgrade `v5.1.0`

**Comment by ajh123** [comment]
Thanks I will look later

**Comment by ajh123** [comment]
@jaywcjlove Everything looks good - however it appears the title of the alerts do not have their fonts set, I assume its a problem with my code instead of this library.

![image](https://github.com/uiwjs/react-markdown-preview/assets/41990982/23b48b7e-270d-4ecb-9888-8ebb74676c37)

My code if you need it: https://github.com/Miners-Online/website-v2

**Comment by ajh123** [comment]
@jaywcjlove It looks right now, Thanks.

![image](https://github.com/uiwjs/react-markdown-preview/assets/41990982/eb50dc78-d3e8-4568-b72f-7979f2870fbe)
