### ISSUE TITLE
Styling ul

### ISSUE THREAD

**Issue by bahpan** [uiwjs/react-markdown-preview#272]
I'm trying to adjust the styling for bullet lists but it doesn't work.
 I made a markdown.css file and passed to component through className prop.
 here my css file:
```
.markdown {
  color: var(--neutral-soft-gray);
  background-color: var(--neutral-dark-gray);
}

.markdown ul {
  margin-left: 10px;
  color: black;
}
```

Can somebody please help me?
thanks in advance

**Comment by jaywcjlove** [comment]
@bahpan Could your style selector be error? ~~`. markdown ul `~~ -> `.markdown ul `

https://github.com/uiwjs/react-markdown-preview/blob/aa3b0d118e4340af9c7805c5666c03931e832298/website/src/App.tsx#L49

**Comment by jaywcjlove** [comment]
```diff
- . markdown ul
+ .markdown ul
```

**Comment by bahpan** [comment]
No I just pasted it here wrongly

**Comment by jaywcjlove** [comment]
@bahpan I can't reproduce the error you're describing. Could you provide me with a sample repository that reproduces the error? I can take a look for you.

**Comment by bahpan** [comment]
I made a sample repo and it works but in another one not. something should be wrong in another project.
thank you by the way
