### ISSUE TITLE
Next.JS Implementation

### ISSUE THREAD

**Issue by jonrrivera** [uiwjs/react-markdown-preview#38]
Hey,

Thanks for the great repo. I found that I cant use this in my next.js app because all global CSS has to be declared on the root component. if there a way to use this without the CSS? I think that should make it work. 

<img width="719" alt="Screen Shot 2020-10-29 at 3 10 19 PM" src="https://user-images.githubusercontent.com/18686388/97638115-21d39e80-19f9-11eb-8697-c91b2d614c1c.png">

Please let me know if you need any more details. thank you!

**Comment by jaywcjlove** [comment]
@jonrrivera https://github.com/uiwjs/react-md-editor/issues/52 Hope it helps you.

**Comment by jaywcjlove** [comment]
@jonrrivera Exmaple: https://codesandbox.io/s/nextjs-example-react-markdown-preview-vuxih?file=/pages/index.js

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

I created a nextjs package [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) to solve the problem.

**Comment by jaywcjlove** [comment]
@jonrrivera

**Comment by AnderUstarroz** [comment]
I made it work by adding this to my `next.config.js file`:
```
const removeImports = require("next-remove-imports")({});

const nextConfig = removeImports({
 your config here...
 ...
 ...
});

module.exports = nextConfig;

```

And the following within my page:
```
import { MarkdownPreviewProps } from "@uiw/react-markdown-preview";


const MarkdownPreview = dynamic<MarkdownPreviewProps>(
  () => import("@uiw/react-markdown-preview"),
  {
    ssr: false,
  }
);

const MyPage: NextPage = () => {
  return (<div><MarkdownPreview source={"Some **markdown** text"} /></div>)
}
```

**Comment by jaywcjlove** [comment]
Example: [@uiwjs/next-remove-imports/example](https://github.com/uiwjs/next-remove-imports/tree/main/example)
