### ISSUE TITLE
Error when upgrading to version 2.0.0

### ISSUE THREAD

**Issue by Timunas** [uiwjs/react-markdown-preview#42]
I started using your project recently and I installed the new version today, but I get this error when rendering the component.

`Uncaught TypeError: combine is not a function` 

![Screenshot from 2020-12-08 19-05-05](https://user-images.githubusercontent.com/18316742/101529336-589dbc80-3988-11eb-84ae-6452b1fe7ef0.png)

It is happening with version 2.0.0 and 2.1.0. So I believe the issue was probably introduced with the react-markdown update.  

I tried downgraded to version 1.0.9 and it is working ok.

**Comment by jaywcjlove** [comment]
@Timunas May be caused by this reason: https://github.com/webpack/webpack/issues/4742

**Comment by jaywcjlove** [comment]
@Timunas https://github.com/remarkjs/react-markdown/issues/518

**Comment by Timunas** [comment]
@jaywcjlove I updated to 2.1.1. And now it is working fine.
