### ISSUE TITLE
Figure with iframe tags break markdown preview

### ISSUE THREAD

**Issue by Kopnu** [uiwjs/react-markdown-preview#87]
Hi, I found a problem with figure/iframe html tags. When You try to add md text right after that, it doesn't compile.
It's easy to reproduce on [codesandbox](https://codesandbox.io/s/react-markdown-preview-forked-oumnx).

Maybe I'm doing the wrong thing and You know a better way to embed a video in a Markdown preview?

Versions:

-     "@uiw/react-markdown-preview": "3.1.1"
-     "react": "17.0.2"
-     "react-dom": "17.0.2"

Some examples:

![image](https://user-images.githubusercontent.com/16706120/122108826-baeee280-ce2d-11eb-8a97-5d6aea01a37c.png)
![image](https://user-images.githubusercontent.com/16706120/122109779-ce4e7d80-ce2e-11eb-90ab-2247849294e2.png)

For other tags, I have to add extra "\n " and it will work...
![image](https://user-images.githubusercontent.com/16706120/122111825-3bfba900-ce31-11eb-9f50-bc625f7aabf1.png)

**Comment by jaywcjlove** [comment]
@Kopnu Use [Remark plugin `@agentofuser/remark-oembed`](https://github.com/agentofuser/remark-oembed)

```jsx
import oembed from '@agentofuser/remark-oembed';

<MarkdownPreview
  source={source}
  remarkPlugins={[oembed]}
/>
```

```markdown
Hey this is a nice youtube video about making modern react apps with gatsby:

https://www.youtube.com/watch?v=GN0xHSk2P8Q

Check it out 👆
```

output

```markdown
Hey this is a nice youtube video about making modern react apps with gatsby:

<iframe 
  width="480" 
  height="270" 
  src="https://www.youtube.com/embed/GN0xHSk2P8Q?feature=oembed" 
  frameborder="0" 
  allow="accelerometer; 
    autoplay; 
    encrypted-media; 
    gyroscope; 
    picture-in-picture" 
  allowfullscreen>
</iframe>

Check it out 👆
```

**Comment by Kopnu** [comment]
@jaywcjlove I don’t know, but I’m really doing something wrong ... 🤔

![image](https://user-images.githubusercontent.com/16706120/122261687-aff78900-cee5-11eb-8db5-bd900c025f28.png)

Where can I find any information on how this should work? Or maybe how can i create my own plugin?
js/react is quite difficult for me, thanks a lot for your help

**Comment by Kopnu** [comment]
Anyway, I found how can I fix this for myself. Bad way but works.

![image](https://user-images.githubusercontent.com/16706120/122272424-98be9880-cef1-11eb-9339-b392c97494db.png)

**Comment by jaywcjlove** [comment]
https://github.com/agentofuser/remark-oembed/issues/154

The plugin is too old

@Kopnu
